name: Deploy to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

    #  - name: Configure AWS Credentials
     #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       #   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #  aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 559050208895.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Docker Image
        run: |
          docker build -t eyego-app .
          docker tag eyego-app:latest 123456789012.dkr.ecr.us-east-1.amazonaws.com/eyego-app:latest
          docker push 123456789012.dkr.ecr.us-east-1.amazonaws.com/eyego-app:latest

      - name: Update Kubernetes Deployment
        run: |
          aws eks update-kubeconfig --name eyego-cluster --region us-east-1 
          kubectl set image deployment/eyego-app eyego-app=123456789012.dkr.ecr.us-east-1.amazonaws.com/eyego-app:latest

